
import requests
import sys
import json
import time

def chat():
    print("🕉️  WhatsApp Hindu Spiritual Agent - CLI Chat")
    print("==============================================")
    print("Type 'quit' or 'exit' to stop.")
    print("Connecting to server at http://127.0.0.1:8000...")

                  
    try:
        health = requests.get("http://127.0.0.1:8000/health")
        if health.status_code == 200:
            print("✅ Server is healthy and connected!")
        else:
            print(f"⚠️  Server responded with status {health.status_code}")
    except requests.exceptions.ConnectionError:
        print("❌ Could not connect to server. Make sure 'venv/bin/uvicorn main:app --reload' is running.")
        return

    subscriber_id = "cli_user_" + str(int(time.time()))

    while True:
        try:
            query = input("\nYou: ")
            if query.lower() in ['quit', 'exit']:
                break
            
            if not query.strip():
                continue

            print("Thinking...", end="", flush=True)
            
                          
            response = requests.post(
                "http://127.0.0.1:8000/api/query",
                params={
                    "query": query,
                    "subscriber_id": subscriber_id
                }
            )
            
            print("\r", end="")                      

            if response.status_code == 200:
                data = response.json()
                
                                                                             
                messages = data.get("messages", [])
                
                print("\nAgent:")
                for msg in messages:
                    print(msg)
                    print("-" * 20)
                
                agents = data.get("agents_used", [])
                if agents:
                    print(f"\n(Generated by: {', '.join(agents)})")
                    
            else:
                print(f"Error: {response.status_code} - {response.text}")

        except KeyboardInterrupt:
            break
        except Exception as e:
            print(f"Error: {e}")

    print("\nGoodbye! Hari Om. 🙏")

if __name__ == "__main__":
    chat()
